# Generated by Django 4.0.4 on 2022-06-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.DecimalField(decimal_places=4, max_digits=50)),
                ('found', models.BooleanField()),
                ('year', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
